name: Docker Image CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build distribution/docker --file distribution/docker/Dockerfile.orkaudio --tag orkaudio:$(date +%s)
