name: Docker CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --file .devcontainer/Dockerfile.orkaudio.build --tag orkaudio:$(date +%s)
    - name: Run oreka build
      uses: ./.github/actions/build-orkaudio

